// <auto-generated />
namespace Vidly2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplyAnnotationToCustomerName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplyAnnotationToCustomerName));
        
        string IMigrationMetadata.Id
        {
            get { return "201912272304263_ApplyAnnotationToCustomerName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.GetSystem.Data.Entity.Migrations.Infrastructure.IMigrationMetadata.Target()
        { return Resources.GetString("Target"); }
    }
}
